#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh

bspc monitor -d I II III IV V

bspc config border_width         2

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^5' state=floating follow=on
bspc rule -a Brave desktop='^1'
bspc rule -a ghostty desktop='^3'
bspc rule -a mplayer3 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
