-- local M = {
--   "nvimdev/lspsaga.nvim",
--   dependencies = {
--     "nvim-tree/nvim-web-devicons",
--     "nvim-treesitter/nvim-treesitter",
--   },
--   config = function()
--     require("lspsaga").setup({})
--   end,
-- }
--
-- return M
--
return {}
