require("secretninjaman.set")
require("secretninjaman.packer")
-- require("secretninjaman.cmp")
require("secretninjaman.telescope")
-- require("secretninjaman.mason")
-- require("secretninjaman.rust-tools")
-- require("secretninjaman.nvim-tree")
require("secretninjaman.nvim-comment")
require("secretninjaman.keymap")
