-- -- Completion framework
-- local M = {
--   "hrsh7th/nvim-cmp",
--   lazy = false,
--   priority = 100,
--   dependencies = {
--     "hrsh7th/cmp-nvim-lsp",
--     "hrsh7th/cmp-nvim-lua",
--     "hrsh7th/cmp-path",
--     "hrsh7th/cmp-buffer",
--
--     "onsails/lspkind-nvim",
--
--     -- LuaSnip
--     { "L3MON4D3/LuaSnip", build = "make install_jsregexp" },
--     "saadparwaiz1/cmp_luasnip",
--   },
--   config = function()
--     require("ext.completion")
--   end,
-- }
--
-- return M
--
return {}
