#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(fd . ~/personal ~/.dotfiles ~/work -d 2 -t d | zf)
fi

if [[ -z $selected ]]; then
    exit 0
fi


selected_name=$(basename "$selected" | tr . _)
session_exists=$(zellij ls | grep $selected_name)

if [[ -n $session_exists ]]; then
  zellij attach $selected_name
  exit 0
fi

# /* if [[ -z $TMUX ]] && [[ -z $zellij_running ]]; then */
# /*     zellij --session $selected_name -c $selected */
# /*     exit 0 */
# /* fi */

zellij options --session-name $selected_name --default-cwd $selected --default-layout my_layout
# zellij attach --create $selected_name
# zellij run --cwd $selected -- nvim
# /* if ! zellij has-session -t=$selected_name 2> /dev/null; then */
# /*     zellij --session $selected_name -c $selected */
# /* fi */
#
# /* zellij switch-client -t $selected_name */
