#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(fd . ~/projects ~/.dotfiles -d 1 -t d | zf)
fi

if [[ -z $selected ]]; then
    exit 0
fi


selected_name=$(basename "$selected" | tr . _)
zellij_running=$(pgrep zellij)

echo $selected_name

# /* if [[ -z $TMUX ]] && [[ -z $zellij_running ]]; then */
# /*     zellij --session $selected_name -c $selected */
# /*     exit 0 */
# /* fi */

zellij options --session-name $selected_name --default-cwd $selected
# zellij attach --create $selected_name
# zellij run --cwd $selected -- nvim
# /* if ! zellij has-session -t=$selected_name 2> /dev/null; then */
# /*     zellij --session $selected_name -c $selected */
# /* fi */
#
# /* zellij switch-client -t $selected_name */
